#!/usr/bin/env python3
"""Turn the measured capability results into one table, so nobody has to read four JSONs.

`probes/capability/run.py` asks an environment around 120 questions and writes the
answers to `probes/capability/results/<name>.json`. This puts every result file side by
side in a single markdown table, one row per check, so a lesson author can look up
whether the thing they are about to depend on exists on the machines this project has
actually measured.

  python tools/gen_capability_matrix.py           regenerate the table
  python tools/gen_capability_matrix.py --check   regenerate in memory and fail on a diff

The output goes to docs/generated/, which is marked linguist-generated, because it is
derived from the results files and editing it by hand would be editing a measurement.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

RESULTS = pathlib.Path("probes/capability/results")
MATRIX = pathlib.Path("docs/generated/capability-matrix.md")

# The order the groups are printed in, and what each one is for. A check whose prefix is
# not in here still appears, at the end, under its own prefix, so adding a check to the
# probe cannot silently drop it out of the table.
GROUPS = [
    ("vm", "What VM this is, and the decisions it made about object layout"),
    ("tool", "Tools in the image, by whether the file is there"),
    ("flag", "Flags the VM accepts. `removed` means it starts, warns and ignores you"),
    ("dcmd", "Diagnostic commands, asked of the MBean that jcmd talks to"),
    ("module", "Modules in the runtime image, whether or not this run resolved them"),
    ("api", "Classes that load, which is a different question from being specified"),
    ("access", "Reflection into java.base with no command line help"),
    ("jfr", "Flight Recorder, and how long it takes to start"),
    ("attach", "Attaching to yourself, which is off unless you ask for it"),
    ("inprocess", "Whether the in process half of the probe ran at all"),
    ("host", "The box rather than the JVM: other tools, permissions, timings"),
]


def load() -> dict[str, dict]:
    files = sorted(RESULTS.glob("*.json"))
    if not files:
        sys.exit(f"no results in {RESULTS}, run probes/capability/run.py first")
    return {path.stem: json.loads(path.read_text(encoding="utf-8")) for path in files}


def show(value: object) -> str:
    """One cell. Booleans get words rather than True and False.

    `yes` and `no` and not a tick and a cross, because this file is read in a terminal
    as often as in a browser and half the terminals in the world render a tick as a box.
    """
    if value is True:
        return "yes"
    if value is False:
        return "no"
    if value is None:
        return "not asked"
    return f"`{value}`"


def column(name: str, data: dict) -> str:
    who = "root" if data.get("privileged") else "user"
    if data.get("privileged") is None:
        # Windows has no euid, and the question does not mean anything there.
        return f"{name}<br>{data['cpus']} cpu"
    return f"{name}<br>{data['cpus']} cpu, {who}"


def build(results: dict[str, dict]) -> str:
    names = list(results)
    keys = sorted(set().union(*[set(d["answers"]) for d in results.values()]))

    same = [
        key for key in keys
        if len({json.dumps(d["answers"].get(key)) for d in results.values()}) == 1
    ]

    out: list[str] = []
    out.append("# Capability matrix")
    out.append("")
    out.append(
        "Generated by `tools/gen_capability_matrix.py` from the files in "
        "`probes/capability/results/`. Do not edit it, edit the measurement. "
        "The report that explains it is [docs/probes/capability.md](../probes/capability.md)."
    )
    out.append("")
    out.append(
        f"{len(keys)} checks on {len(names)} environments, all on java "
        f"{results[names[0]]['java_build']}. {len(same)} of the checks give the same "
        f"answer everywhere and {len(keys) - len(same)} do not."
    )
    out.append("")

    for name in names:
        data = results[name]
        out.append(
            f"- **{name}** is {data['platform']}, {data['cpus']} cpus, measured "
            f"{data['measured'][:10]}"
        )
    out.append("")

    header = "| check | " + " | ".join(column(n, results[n]) for n in names) + " |"
    divider = "|---|" + "---|" * len(names)

    seen: set[str] = set()
    prefixes = [g[0] for g in GROUPS]
    extra = sorted({k.split(".")[0] for k in keys} - set(prefixes))
    for prefix, blurb in GROUPS + [(p, "") for p in extra]:
        rows = [k for k in keys if k.split(".")[0] == prefix and k not in seen]
        if not rows:
            continue
        seen.update(rows)
        out.append(f"## {prefix}")
        out.append("")
        if blurb:
            out.append(blurb + ".")
            out.append("")
        out.append(header)
        out.append(divider)
        for key in rows:
            cells = " | ".join(show(results[n]["answers"].get(key)) for n in names)
            out.append(f"| `{key}` | {cells} |")
        out.append("")

    notes = sorted(
        {(key, note) for d in results.values() for key, note in d["notes"].items()}
    )
    if notes:
        out.append("## Why the noes")
        out.append("")
        out.append(
            "Every check that answered no and had something to say about it. "
            "The same check can appear twice if two environments refused differently."
        )
        out.append("")
        for key, note in notes:
            out.append(f"- `{key}`: {note}")
        out.append("")

    return "\n".join(out)


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="fail if the committed file differs")
    args = ap.parse_args(argv)

    wanted = build(load())
    if args.check:
        if not MATRIX.is_file():
            print(f"{MATRIX} is missing, run tools/gen_capability_matrix.py", file=sys.stderr)
            return 1
        if MATRIX.read_text(encoding="utf-8") != wanted:
            print(
                f"{MATRIX} does not match {RESULTS}, run tools/gen_capability_matrix.py",
                file=sys.stderr,
            )
            return 1
        print(f"the capability matrix matches {RESULTS}")
        return 0

    MATRIX.parent.mkdir(parents=True, exist_ok=True)
    MATRIX.write_text(wanted, encoding="utf-8")
    print(f"wrote {MATRIX}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
